# Generated by Django 4.0.6 on 2022-07-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_user_my_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_User',
            new_name='MyUser',
        ),
    ]
