# Generated by Django 4.0.6 on 2022-07-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_my_user_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='courses.myuser'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='learning on djnago by Dariush', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
