# Generated by Django 4.0.6 on 2022-07-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students_remove_course_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(verbose_name='Description about course!'),
        ),
    ]
