# Generated by Django 4.0.6 on 2022-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='./images/course_pictures', verbose_name='image of course'),
        ),
    ]
