# Generated by Django 4.0.6 on 2022-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='static/assets/images/course_picture', verbose_name='image of course'),
        ),
    ]
