# Generated by Django 4.0.6 on 2022-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='tweeter',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/assets/images/profile_pictures'),
        ),
    ]
