# Generated by Django 4.0.6 on 2022-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_myuser_github_remove_myuser_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='github',
            field=models.URLField(default='hi', max_length=100, unique=True, verbose_name='github'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='instagram',
            field=models.URLField(default='hi', max_length=100, unique=True, verbose_name='instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='linkedin',
            field=models.URLField(default='1', max_length=100, unique=True, verbose_name='linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='personal_website',
            field=models.URLField(default='sd', max_length=100, unique=True, verbose_name='personal website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='telegram',
            field=models.URLField(default='we', max_length=100, unique=True, verbose_name='telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='tweeter',
            field=models.URLField(default='33e', max_length=100, unique=True, verbose_name='tweeter'),
            preserve_default=False,
        ),
    ]
