# Generated by Django 4.0.6 on 2022-08-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_myuser_github_myuser_instagram_myuser_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='tweeter',
        ),
    ]
