# Generated by Django 4.0.6 on 2022-08-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_myuser_about_me_alter_myuser_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
