# Generated by Django 4.0.6 on 2022-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_myuser'),
        ('courses', '0014_alter_myuser_about_me_alter_myuser_github_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='accounts.profile'),
        ),
    ]
