# Generated by Django 4.0.6 on 2022-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_delete_myuser_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
