# Generated by Django 4.0.6 on 2022-08-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_digital_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
