# Generated by Django 4.0.6 on 2022-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='1', height_field='224px', upload_to='static/assets/images/article_pictures/', width_field='346px'),
            preserve_default=False,
        ),
    ]
