# Generated by Django 4.0.6 on 2022-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_description', models.CharField(max_length=500, verbose_name='Description about course!')),
                ('course_image', models.ImageField(upload_to='../images/course_pictures', verbose_name='image of course')),
                ('course_link_to_zoom', models.URLField(max_length=256, verbose_name='zoom link')),
                ('Course_data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('title', models.CharField(max_length=256)),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('location', models.CharField(max_length=100, verbose_name='address')),
                ('about_me', models.TextField(max_length=1000, verbose_name='a little about about your profile!')),
                ('profile_pic', models.ImageField(blank=True, upload_to='./images/profile_pictures')),
                ('telegram', models.URLField(max_length=100, unique=True, verbose_name='telegram')),
                ('github', models.URLField(max_length=100, unique=True, verbose_name='github')),
                ('linkedin', models.URLField(max_length=100, unique=True, verbose_name='linkedin')),
                ('tweeter', models.URLField(max_length=100, unique=True, verbose_name='tweeter')),
                ('instagram', models.URLField(max_length=100, unique=True, verbose_name='instagram')),
                ('personal_website', models.URLField(max_length=100, unique=True, verbose_name='personal website')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.ManyToManyField(to='articles.user'),
        ),
    ]
