# Generated by Django 4.0.6 on 2022-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('title', models.CharField(max_length=256)),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('location', models.CharField(max_length=100, verbose_name='address')),
                ('about_me', models.TextField(max_length=1000, verbose_name='a little about about your profile!')),
                ('profile_pic', models.ImageField(blank=True, upload_to='./images/profile_pictures')),
                ('telegram', models.URLField(max_length=100, unique=True, verbose_name='telegram')),
                ('github', models.URLField(max_length=100, unique=True, verbose_name='github')),
                ('linkedin', models.URLField(max_length=100, unique=True, verbose_name='linkedin')),
                ('tweeter', models.URLField(max_length=100, unique=True, verbose_name='tweeter')),
                ('instagram', models.URLField(max_length=100, unique=True, verbose_name='instagram')),
                ('personal_website', models.URLField(max_length=100, unique=True, verbose_name='personal website')),
            ],
        ),
    ]
