# Generated by Django 4.0.6 on 2022-08-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_full_name',
        ),
    ]
