# Generated by Django 4.0.6 on 2022-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/assets/images/profile_pictures/default.png', upload_to='static/assets/images/profile_pictures'),
        ),
    ]
