# Generated by Django 4.0.6 on 2022-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/assets/images/profile_pictures/IMG_0610_KLaTRxP.jpg', upload_to='static/assets/images/profile_pictures'),
        ),
    ]
