# Generated by Django 4.0.6 on 2022-08-08 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=ckeditor.fields.RichTextField(default='1'),
            preserve_default=False,
        ),
    ]
