# Generated by Django 4.0.6 on 2022-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='a little about about your profile!'),
        ),
    ]
