# Generated by Django 4.0.6 on 2022-08-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/assets/images/profile_pictures/default.png', null=True, upload_to='static/assets/images/profile_pictures'),
        ),
    ]
