# Generated by Django 4.0.6 on 2022-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_course_students'),
        ('accounts', '0017_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_of_registered_courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
    ]
